# Generated by Django 3.1.5 on 2021-01-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=800)),
                ('detail_discription', models.TextField()),
                ('project_url', models.URLField(max_length=500)),
                ('project_github_url', models.URLField(max_length=800)),
                ('tech_used_one', models.CharField(max_length=200)),
                ('tech_used_two', models.CharField(max_length=200)),
                ('tech_used_three', models.CharField(max_length=200)),
                ('tech_used_four', models.CharField(max_length=200)),
                ('tech_used_five', models.CharField(max_length=200)),
                ('tech_used_six', models.CharField(max_length=200)),
                ('project_main_image', models.ImageField(upload_to='media/projects/%Y/%m/')),
                ('project_ss_one', models.ImageField(upload_to='media/projects/%Y/%m/')),
            ],
        ),
    ]
