# Generated by Django 3.1.5 on 2021-01-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_ss_five',
            field=models.ImageField(blank=True, upload_to='media/projects/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_ss_four',
            field=models.ImageField(blank=True, upload_to='media/projects/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_ss_six',
            field=models.ImageField(blank=True, upload_to='media/projects/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_ss_three',
            field=models.ImageField(blank=True, upload_to='media/projects/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_ss_two',
            field=models.ImageField(blank=True, upload_to='media/projects/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_main_image',
            field=models.ImageField(blank=True, upload_to='media/projects/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_ss_one',
            field=models.ImageField(blank=True, upload_to='media/projects/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_used_five',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_used_four',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_used_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_used_six',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_used_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_used_two',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
